# fly.toml app configuration file generated for cmdcast on 2023-10-04T22:35:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cmdcast"
primary_region = "ams"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
